using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DashboardData.Library.Models
{
    public class StockSymbolDataModel
    {
        //Id value used as a placeholder. Id is autogenerated by stored procedure.
        public int Id { get; set; }
        public string StockSymbol { get; set; }
    }
}
